- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: App pre requisite
  ansible.builtin.import_tasks: app-preq.yml

- name: Download Maven dependencies
  ansible.builtin.shell: mvn clean package ; mv target/${component}-1.0.jar ${component}.jar
  args:
    chdir: /app

- name: Schema setup
  ansible.builtin.import_tasks: mysql-schema.yml
  when: schema is defined

- name: systemD setup
  ansible.builtin.import_tasks: systemd-setup.yml




  echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>>>>>>> Create ${component} service <<<<<<<<<<<<<<<<<<<<<<<\e[0m" | tee -a /tmp/roboshop.log
  cp ${component}.service /etc/systemd/system/${component}.service  &>>${log}
  func_exit_status
  
  echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>> Install Maven <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m" | tee -a /tmp/roboshop.log
  yum install maven -y  &>>${log}
  func_exit_status
  
  
  func_apppreq
  
  echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>> Build ${component} service <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m" | tee -a /tmp/roboshop.log
  mvn clean package  &>>${log}
  mv target/${component}-1.0.jar ${component}.jar  &>>${log}
  func_exit_status
  
  func_schema_setup
  
  func_systemd

