- name: copy Mongodb Yum repo file
  src: mongo.repo
  dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load schema
  ansible.builtin.shell: mongo --host mongodb-dev.akhildevops.online </app/schema/{{component}}.js