- name: Install python
  ansible.builtin.yum:
    name: python
    state: installed

- name: App pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: download maven dependencies 
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: systemD setup
  ansible.builtin.import_tasks: systemd-setup.yml