
#echo "\e[36m>>>>>>>>>>>>>copy the roboshop configuration<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
#cp nginx-roboshop.conf /etc/nginx/default.d/roboshop.conf &>>${log}
#func_exit_status

#echo "\e[36m>>>>>>>>>>>>>Remove the existing content<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
#rm -rf /usr/share/nginx/html/* &>>${log}
#func_exit_status

#echo "\e[36m>>>>>>>>>>>>>Download the app content<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>${log}
#func_exit_status

#echo "\e[36m>>>>>>>>>>>>>change the Directory<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
#cd /usr/share/nginx/html &>>${log}
#func_exit_status

#echo "\e[36m>>>>>>>>>>>>>Extract the Frontend content<<<<<<<<<<<<<<\e[0m" | tee -a ${log}
#unzip /tmp/frontend.zip &>>${log}
#func_exit_status



- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

