- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy RoboShop Configuration - Project Config
  ansible.builtin.template:
    src: nginx-roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Clean old content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download and extract application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: ReStart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes



