- name: copy mysql  repo configuration
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
- name: Disable mysql module
  ansible.builtin.shell: yum module disable mysql -y
- name: Install mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed
- name: Restart the mysql service
  ansible.builtin.systemd:
    name: mysqld
    enabled: true
    state: restarted
- name: Set mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass Roboshop@1