
- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: Clean Old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download and extract application content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Download and extract application content from Nexus
  ansible.builtin.unarchive:
    src: http://{{username}}:{{password}}@172.31.36.234:8081/repository/{{component}}/{{component}}-{{appversion}}.zip
    dest: /app
    remote_src: yes
  vars:
    username: "{{ lookup('amazon.aws.aws_ssm', 'nexus.username', region='us-east-1') }}"
    password: "{{ lookup('amazon.aws.aws_ssm', 'nexus.password', region='us-east-1') }}"
    appVersion: "{{ lookup('amazon.aws.aws_ssm', '{{component}}.{{env}}.{{appVersion}}', region='us-east-1') }}"

