- name: copy mongodb repo configuration
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load schema
  ansible.builtin.shell: mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', 'docdb.{{var.env}}.endpoint', region='us-east-1') }}:27017 --sslCAFile global-bundle.pem --username docdbadmin --password roboshop1234 </app/schema/{{component}}.js
  when: schema is defined
