#- name: check nodejs is installed
#  ansible.builtin.shell: type npm
#  register: command_status
#  ignore_errors: yes

- name: Install Nodejs repos
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash
#  when: command_status.rc != 0

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed
#  when: command_status.rc != 0

- name: App-prerequisite
  ansible.builtin.import_tasks: app-prerequisite.yml

#- name: Download NodeJS Dependencies
#  ansible.builtin.shell: npm install
#  args:
#    chdir: /app

- name: schema setup
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: systemd setup
  ansible.builtin.import_tasks: systemd.yml

