
- name: Install NodeJs Repos
  ansible.builtin.shell: yum module disable nodejs -y ; yum module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: download nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: schema setup
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: systemD setup
  ansible.builtin.import_tasks: systemd-setup.yml

