- name: install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: App pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: download python dependencies 
  ansible.builtin.shell: pip3.6 install -r requirement.txt
  args:
    chdir: /app

- name: systemD setup
  ansible.builtin.import_tasks: systemd-setup.yml